### ISSUE TITLE
How to read scaling.data?

### ISSUE THREAD

**Issue by yanxon** [materialsvirtuallab/mlearn#4]
Hi,

I have a question regarding the scaling.data. For example here:
https://github.com/materialsvirtuallab/mlearn/blob/7606e2106607a12c89d6dbcd93ba658ad60f1938/mvl_models/Cu/nnp/scaling.data#L1

What are the columns representing?

**Comment by YunxingZuo** [comment]
@yanxon Hi!

The scaling.data stores the scaling information of the symmetry functions. This file was generated by [nnp-scaling](https://compphysvienna.github.io/n2p2/Tools/nnp-scaling.html?highlight=scaling) tool in the original package [n2p2](https://github.com/CompPhysVienna/n2p2). As you can see in the input.nn, there are 27 symmetry functions, so the second column represents the index of each symmetry function. The first column represents the index of elements in the training set (here we only have 1 element). The third, fourth, fifth, and sixth columns represent the minimum, maximum, mean, and sigma of each symmetry function for all atoms of specific type (Cu in this case). This file is a prerequisite for training a neural network potential.

**Comment by yanxon** [comment]
Hi @YunxingZuo,

Thank you for the response. 

I have a follow-up question. What type of the scalings that is used in the Si, Mo, and Cu NNP models? Is it ST_SCALESIGMA? I got the reference from [here](https://compphysvienna.github.io/n2p2/doc-exhale/classnnp_1_1SymmetryFunction.html#_CPPv4N3nnp16SymmetryFunction11ScalingTypeE).

**Comment by YunxingZuo** [comment]
@yanxon Hi,

As you can see in the input.nn files for Si, Mo, and Cu NNP models, there are keywords called "scale_symmetry_functions", which indicate that the type of scaling is ST_SCALE. For keywords of other types of scaling, pls see the [documentation](https://compphysvienna.github.io/n2p2/Topics/keywords.html).

**Comment by yanxon** [comment]
Thank you @YunxingZuo ,

I see it now. I have one last question. The symmetry parameters for Si NNP in [mlearn](https://github.com/materialsvirtuallab/mlearn/blob/master/mvl_models/Si/nnp/input.nn) are different than the parameters reported in the Arxiv paper. What is the reason for this?

**Comment by YunxingZuo** [comment]
@yanxon Hi,

If I understand your question correctly, you may want to ask why the values of symmetry parameters in input.nn are different from that in the paper? The reason is that we used **Angstrom** as the unit in the paper but used **Bohr** as the unit in the input.nn (default setting in n2p2). There is a factor of 0.529177. For example, the optimized cutoff of Si NNP in the paper is 5.2 Angstrom, the cutoff values in the input.nn are 5.2/0.529177 = 9.8265759 Bohr. If you use the mlearn repo to train your own NNP (with n2p2 underneath), you will just need to define the cutoff radius in Angstrom, the code will automatically transform it into Bohr.
